### ISSUE TITLE
Wii builds from release 1.4 onward have a sound problem

### ISSUE THREAD

**Issue by beerbarian9000** [libretro/fbalpha2012_neogeo#13]
Last build of this core on Wii with normal sound was fb_alpha_neo_libretro.dol from the 1.3.6 release.
That core declares itself as v0.2.97.30
Releases 1.4.0, 1.4.1 and 1.5.0 have distorted sound.
fbalpha2012_neogeo_libretro_wii.dol in the 1.5.0 release declares itself as v0.2.97.29
both the 1.4.0 and 1.4.1 cores show v0.2.97.30

**Comment by beerbarian9000** [comment]
I think this issue might be more widespread.
I just tried this core for x86 Windows and it has the same sound problems.
I couldn't see this reported on the forum so I thought to make mention of it here.
If its preferred to have bug reports back on the forum please let me know.
The FBA 2012 core for Windows x86 (0.2.97.29) runs Neo Geo with normal sound.
The current FBA core for Windows x86 (0.2.97.40) has even worse distorted audio for Neo Geo.

**Comment by danieljg** [comment]
I can confirm this bug in the wii version. However, this sound error (high frequency ringing, very bothersome) doesn't appear in the same core under arch linux 64 bit for me.

Downloading the core doesn't seem to install a *.info file, either, but that's to be filed as another bug at some point.

**Comment by beerbarian9000** [comment]
Sound issue persists through the 1.6 releases and also in 1.7.0

**Comment by beerbarian9000** [comment]
Latest release 1.7.3 for Wii has fixed those nagging audio problems for Neo Geo core.
Closing this issue! 🥇

**Comment by danieljg** [comment]
@beerbarian9000 Thanks for letting us know!  I'll be sure to hook up the wii tonight for some neo geo goodness.

Any clue as to what actually caused issue or what the fix was?

**Comment by beerbarian9000** [comment]
No clue @danieljg sorry. I know it probably should be detailed for proper closure, but as the user who opened this issue I decided just to close it out since it's fixed now. Maybe it's detailed in notes/comments elsewhere.
